SELECT * FROM spring_batch.BATCH_JOB_EXECUTION;

SELECT * FROM spring_batch.BATCH_JOB_EXECUTION_CONTEXT;

SELECT * FROM spring_batch.BATCH_JOB_EXECUTION_PARAMS;

SELECT * FROM spring_batch.BATCH_JOB_EXECUTION_SEQ;

SELECT * FROM spring_batch.BATCH_JOB_INSTANCE;

SELECT * FROM spring_batch.BATCH_JOB_SEQ;

SELECT * FROM spring_batch.BATCH_STEP_EXECUTION;

SELECT * FROM spring_batch.BATCH_STEP_EXECUTION_CONTEXT;

SELECT * FROM spring_batch.BATCH_STEP_EXECUTION_SEQ;